// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtQBONFsC8joCfEbRZ9RBXS5zD6ZTtvU',
    appId: '1:217346028104:web:36dcfc4ccb7a3b2c4c9e7d',
    messagingSenderId: '217346028104',
    projectId: 'holachat-3d497',
    authDomain: 'holachat-3d497.firebaseapp.com',
    storageBucket: 'holachat-3d497.appspot.com',
    measurementId: 'G-1NWNT31ZFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRyslTVgYIH168ZJZF0zYqkneMb72u2A',
    appId: '1:217346028104:android:ed115c14676c971a4c9e7d',
    messagingSenderId: '217346028104',
    projectId: 'holachat-3d497',
    storageBucket: 'holachat-3d497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS0pFSsCi605EPmSaNpBg9Z3vFaLpY9jQ',
    appId: '1:217346028104:ios:1cd647ec69c5b67b4c9e7d',
    messagingSenderId: '217346028104',
    projectId: 'holachat-3d497',
    storageBucket: 'holachat-3d497.appspot.com',
    iosBundleId: 'com.example.hola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS0pFSsCi605EPmSaNpBg9Z3vFaLpY9jQ',
    appId: '1:217346028104:ios:43d4447275a030c64c9e7d',
    messagingSenderId: '217346028104',
    projectId: 'holachat-3d497',
    storageBucket: 'holachat-3d497.appspot.com',
    iosBundleId: 'com.example.hola.RunnerTests',
  );
}
